import type { Metadata } from "next";
import { JetBrains_Mono, Orbitron } from "next/font/google";
import { usePathname } from "next/navigation";
import { AnimatePresence } from "framer-motion";
import Transition from "./components/transition";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const caseOrbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "霜月",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${orbitron.variable} antialiased`}>
        <AnimatePresence mode="wait">
          <div key={pathname}>
            <Transition />
            {children}
          </div>
        </AnimatePresence>
      </body>
    </html>
  );
}