import type { Metadata } from "next";
import { Quicksand, Orbitron, Press_Start_2P, Fredoka, Nunito, Pixelify_Sans } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
// import Menu from "@/components/layout/menu/Menu";

const caseQuicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const caseOrbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const pressStart = Press_Start_2P({
  variable: "--font-press-start",
  subsets: ["latin"],
  weight: "400",
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

const pixelify = Pixelify_Sans({
  variable: "--font-pixelify",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "RA/FA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caseQuicksand.variable} ${caseOrbitron.variable} ${pressStart.variable} ${fredoka.variable} ${nunito.variable} ${pixelify.variable} antialiased`}
      >
        {/* <Menu /> */}
        <Script
          strategy="lazyOnload"
          src="//code.tidio.co/uwxsz6qiplidpo3cjoqwat1sapidgdna.js"
        />
        {children}
      </body>
    </html>
  );
}