import type { Metadata } from "next";
import { JetBrains_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
// import Menu from "./components/layout/menu/Menu"; // <-- 1. IMPORT IT FIRST!
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const caseOrbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "霜月",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`${jetbrainsMono.variable} ${orbitron.variable} antialiased`}>
        <AnimatePresence mode="wait">
          <div key={pathname}>
            <Transition />
            {children}
          </div>
        </AnimatePresence>
=======
      <body
        className={`${jetbrainsMono.variable} ${caseOrbitron.variable} antialiased`}
      >
         {/* <-- 2. PLACE IT RIGHT HERE! */}
        <Script
          strategy="lazyOnload"
          src="//code.tidio.co/uwxsz6qiplidpo3cjoqwat1sapidgdna.js"
        />
        {children}
>>>>>>> parent of 3f828bc (before bb)
      </body>
    </html>
  );
}